### ISSUE TITLE
Dynmap support

### ISSUE THREAD

**Issue by mrbreil** [lulucraft/-HideRails-#4]
Unfortunately the iron bars are rendered on the dynmap map. Can you deactivate it somehow.

Regards Mr. Breil

**Comment by lulucraft** [comment]
Hi,

Following our discussion on discord.

HideRails plugin just send packets to players to hide blocks only for player. No modification is made on the server side.
The blocks stay placed and they are not removed from the world.
So, I can't fix it sorry :confused:

But I have asked the Dynmap plugin author to confirm my hypotheses
And if the dynmap author found solution, I will publish a patch.

Best Regards,
Nepta_
